name: Deploy WhatsApp Bot to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_ci_cd
          chmod 600 ~/.ssh/id_rsa_ci_cd
          ssh-keyscan -H 8.215.36.233 >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_rsa_ci_cd -o StrictHostKeyChecking=no root@8.215.36.233 << 'EOF'
            cd /root/whatsapp-baileys
            git pull origin main
            pm2 restart whatsapp-bot || pm2 start src/server.js --name whatsapp-bot
          EOF
