name: Deploy WhatsApp Bot to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_DEPLOY_KEY }}" > ~/.ssh/id_rsa_ci_cd
          chmod 600 ~/.ssh/id_rsa_ci_cd
          ssh-keyscan -p 22 8.215.36.233 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_ci_cd root@8.215.36.233 -p 22 << 'EOF'
            cd /root/whatsapp-baileys
            git pull origin main
            pm2 restart all || pm2 start src/server.js --name whatsapp-bot
          EOF

