name: Deploy WhatsApp Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_rsa_ci_cd -o StrictHostKeyChecking=no root@8.215.36.233 << 'EOF'
            cd /root/whatsapp-baileys
            git pull origin main
            /root/.nvm/versions/node/v23.11.0/bin/pm2 restart whatsapp-bot || /root/.nvm/versions/node/v23.11.0/bin/pm2 start src/server.js --name whatsapp-bot
          EOF
        env:
          NODE_ENV: production
