name: Deploy WhatsApp Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_ci_cd
          chmod 600 ~/.ssh/id_rsa_ci_cd
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - name: Deploy to VPS via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          NODE_ENV: production
        run: |
          ssh -i ~/.ssh/id_rsa_ci_cd -o StrictHostKeyChecking=no root@$SSH_HOST << 'EOF'
            export PATH=/root/.nvm/versions/node/v23.11.0/bin:$PATH
            cd /root/whatsapp-baileys
            git pull origin main
            pm2 restart whatsapp-bot || pm2 start src/server.js --name whatsapp-bot
          EOF
